Update TuningSchema.json
odgaard/TuningSchema pull request #8
Opened 2024-06-24 12:17 UTC by jpazurikova

Based on the discussion we had, I propose to add properties
- Device into KernelSpecification. Device consists of Id (this is how the device for the execution is set, default 0) and Name (to increase readability, the user can note here that device with id 0 is e.g. GPU Nvidia GTX 1070). Not required, if specified, Id needs to be set.
- Profiling into KernelSpecification. Boolean, if true, profiling is turned on. Default false. Not required.
- random seed for every kernel Argument and ReferenceArgument. Applicable when the data are randomly generated, i.e. FillType Random, in some cases also Generator and Script. Not required.

Note: The random seed for the search method can be specified as one of Attributes in Search.

I also propose to remove KernelTypeNames as these are not applied in any autotuner and their initial purpose is not clear.

2024-06-24 12:50 UTC, jpazurikova commented
I also added validation details (method and threshold) for reference arguments.

2024-07-03 14:14 UTC, odgaard requested changes

2024-07-03 14:14 UTC, odgaard commented on TuningSchema.json
> +                            "type: "integer"
Typo here. Missing end quote for type.

2024-07-03 14:14 UTC, odgaard commented on TuningSchema.json
> +                                "SideBySideRelativeComparison"
Could you provide documentation for what the difference is between these three validation methods? I couldn't find it in your pdf detailing the changes.

2024-07-04 06:52 UTC, jpazurikova commented on TuningSchema.json
> +                            "type: "integer"
Sorry, done. After further thought, I've also removed the requirement for DeviceId. If the user just want to note the name of a single device for future better readability, they should be able to do so without (needlessly) specifying device id.

2024-07-04 06:53 UTC, jpazurikova commented on TuningSchema.json
> +                                "SideBySideRelativeComparison"
Sure,
AbsoluteDifference: Calculates sum of differences between each pair of elements, then compares the sum to specified threshold. 
SideBySideComparison: Calculates difference for each pair of elements, then compares the difference to specified threshold. 
SideBySideRelativeComparison: Calculates difference for each pair of elements, then compares the difference divided by reference value to the specified threshold.

I'll add the descriptions into the document.

2024-07-05 07:20 UTC, odgaard approved these changes
Great! Looks good now.

2024-07-05 07:21 UTC, merged